version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: course_pg
    environment:
      POSTGRES_USER: course_admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: course_select
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - '55432:5432'
  redis:
    image: redis:7-alpine
    ports:
      - '6380:6379'
